---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: "core"

deepvariant:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 1024
  partition: "gpu"
  gres: "gpu:1"

fq2bam:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 1024
  partition: "gpu"
  gres: "gpu:1"

mutectcaller:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 1024
  partition: "gpu"
  gres: "gpu:1"
