$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: path to reference fasta file
      genome_dir:
        type: string
        description: path to reference directory
      sites:
        type: string
        description: path to known sites list file
    required:
      - fasta
      - sites
  required:
    - samples
    - units
    - resources
    - reference

  deepvariant:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for deepvariant

  fq2bam:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for fq2bam

  mutectcaller:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for mutectcaller

  rna_fq2bam:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for rna_fq2bam
      extra:
        type: string
        description: parameters that should be forwarded to rna_fq2bam
