$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: path to reference fasta file
      genome_dir:
        type: string
        description: path to STAR reference directory
      sites:
        type: string
        description: path to known sites list file
    required:
      - fasta
      - sites
  deepvariant:
    type: object
    description: parameters for deepvariant
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
  fq2bam:
    type: object
    description: parameters for fq2bam
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
  mutectcaller:
    type: object
    description: parameters for mutectcaller
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
  rna_fq2bam:
    type: object
    description: parameters for rna_fq2bam
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      extra:
        type: string
        description: parameters that should be forwarded
required:
  - reference
  - resources
  - samples
  - units
