name: Lint

on:
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: ".tests/integration"
          snakefile: "workflow/Snakefile"
          args: "--lint"
          stagein: "pip install -r requirements.txt"
