from hydra_genetics.utils.resources import load_resources


rule all:
    input:
        "parabricks/pbrun_deepvariant/NA12878_N.vcf",
        "parabricks/pbrun_mutectcaller_t/NA12878_T.vcf",
        "parabricks/pbrun_mutectcaller_tn/NA12878.vcf",
        "parabricks/pbrun_rna_fq2bam/NA12878_R.bam",


configfile: "config.yaml"


config = load_resources(config, config["resources"])


def extract_module_version_from_readme(modulename):
    search_string = modulename + ":(.+)\n$"
    with open("../../README.md", "r") as reader:
        for line in reader:
            result = re.search(search_string, line)
            if result:
                return result[1]


module prealignment:
    snakefile:
        github(
            "hydra-genetics/prealignment",
            path="workflow/Snakefile",
            tag=extract_module_version_from_readme("prealignment"),
        )
    config:
        config


use rule * from prealignment as prealignment_*


module parabricks:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config


use rule * from parabricks as parabricks_*
